name: perlpack

on: workflow_dispatch

env:
  MAKEFLAGS: -j2

jobs:
  perlpack:
    runs-on: ubuntu-24.04
    container: alpine:3.19
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils cmake git wget curl perl gperf autoconf automake libtool pkgconfig # python3 && ln -sf python3 /usr/bin/python

      - uses: actions/checkout@v4
      
      - name: Build Perl
        run: make build/libperl.a
      
      - name: Build and test perlpackstatic
        run: |
          make perlpackstatic
          ./perlpackstatic
          ./perlpackstatic -e 'use Cwd;print(Cwd::cwd(),"\n");'
          ./perlpackstatic -e 'open(F,"<","/mnt/perlpack/lib/5.40.0/x86_64-linux/Cwd.pm");print(<F>);'
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            packfs.h
            perlpackstatic
            #packfs.h.o/
