name: perlpack

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.35.4.tar.gz
  MAKEFLAGS: -j2

jobs:
  perlpack:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils cmake git xz wget perl gperf p7zip python3 strace && ln -sf python3 /usr/bin/python

      - uses: actions/checkout@v2

      - name: Build Native Perl
        run: |
          export MAKEFLAGS
          mkdir build
          wget -nc $URLPERL
          tar -xf $(basename $URLPERL) --strip-components=1 --directory=build
          
          cd build
          sh ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix=../prefix -Aldflags=-lm -Accflags=-lm -Dstatic_ext="IO Fcntl  Cwd Opcode re mro B Socket POSIX attributes Storable Data/Dumper MIME/Base64 Digest/MD5 Digest/SHA Encode Encode/CN Encode/Unicode Encode/TW Encode/JP Encode/KR  Encode/Byte Encode/EBCDIC Encode/Symbol threads threads/shared Sys/Syslog Sys/Hostname Time/HiRes Time/Piece Unicode/Normalize Unicode/Collate Compress/Raw/Zlib Compress/Raw/Bzip2 PerlIO/scalar PerlIO/encoding PerlIO/via PerlIO/mmap Devel/Peek IPC/SysV File/Glob File/DosGlob Hash/Util Hash/Util/FieldHash Filter/Util/Call  I18N/Langinfo List/Util Math/BigInt/FastCalc SDBM_File" -Dusedevel -Dlibs="-lpthread -ldl -lm -lutil -lc"
          make miniperl generate_uudmap
          make perl
          make install
          cd ..
           
          #gcc -o perlpack perlpack.c myscript.o  -I$PWD/build -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Ibuild/prefix/lib/perl5/*/x86_64-linux/CORE      -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib                         build/prefix/lib/perl5/*/x86_64-linux/auto/Fcntl/Fcntl.a build/prefix/lib/perl5/*/x86_64-linux/auto/IO/IO.a build/prefix/lib/perl5/*/x86_64-linux/auto/Cwd/Cwd.a build/prefix/lib/perl5/*/x86_64-linux/auto/Encode/Unicode/Unicode.a build/prefix/lib/perl5/*/x86_64-linux/CORE/libperl.a -lpthread -ldl -lm -lutil -lc -lm 
          #echo CORE
          #find build/prefix/lib/perl5/*/x86_64-linux/CORE -name '*.h'
          #echo GENERIC
          #find build -name '*.h'
          #echo END
          
          # -Ibuild/prefix/lib/perl5/*/x86_64-linux/CORE
          
          ld -r -b binary -o myscript.o myscript.pl
          cc -o perlpack perlpack.c myscript.o  -I$PWD/build -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64     -Wl,-E -fstack-protector-strong -fwrapv -fno-strict-aliasing -L/usr/local/lib   $(printf "build/lib/auto/%s " mro/mro.a Devel/Peek/Peek.a File/DosGlob/DosGlob.a File/Glob/Glob.a Sys/Syslog/Syslog.a Sys/Hostname/Hostname.a PerlIO/via/via.a PerlIO/mmap/mmap.a PerlIO/encoding/encoding.a PerlIO/scalar/scalar.a B/B.a attributes/attributes.a Unicode/Normalize/Normalize.a Unicode/Collate/Collate.a threads/threads.a threads/shared/shared.a IPC/SysV/SysV.a re/re.a Digest/MD5/MD5.a Digest/SHA/SHA.a SDBM_File/SDBM_File.a Math/BigInt/FastCalc/FastCalc.a Data/Dumper/Dumper.a I18N/Langinfo/Langinfo.a Time/HiRes/HiRes.a Time/Piece/Piece.a IO/IO.a Socket/Socket.a Hash/Util/FieldHash/FieldHash.a Hash/Util/Util.a Filter/Util/Call/Call.a POSIX/POSIX.a Encode/Unicode/Unicode.a Encode/Encode.a Encode/JP/JP.a Encode/KR/KR.a Encode/EBCDIC/EBCDIC.a Encode/CN/CN.a Encode/Symbol/Symbol.a Encode/Byte/Byte.a Encode/TW/TW.a Compress/Raw/Zlib/Zlib.a Compress/Raw/Bzip2/Bzip2.a MIME/Base64/Base64.a Cwd/Cwd.a Storable/Storable.a List/Util/Util.a Fcntl/Fcntl.a Opcode/Opcode.a) build/libperl.a -lpthread -ldl -lm -lutil -lc -lm 
          ldd ./perlpack || true
          ./perlpack
      
      - name: Test Native Perl
        run: |
          git clone https://github.com/busytex/busyfs
          mv prefix busyfs/packfs
          
          cd busyfs
          rm -rf packfs/man packfs/lib/*/pod/ || true
          find packfs -name '*.pod' -delete
          find packfs -name '*.ld' -delete
          find packfs -name '*.a' -delete
          find packfs -name '*.h' -delete
          python packfs.py -i packfs -o packfs.h
          cc -shared -fPIC packfs.c -o packfs.so -ldl @packfs.h.txt
          find packfs -name '*.o' -delete
          cd ..

          export PERL_DL_DEBUG=1
          #strace -ff -e trace=file,read,write,close
          LD_PRELOAD=$PWD/busyfs/packfs.so PERLLIB=packfs/lib/perl5/5.35.4:packfs/lib/perl5/5.35.4/x86_64-linux ./perlpack -e 'use Cwd;print(Cwd::cwd()."\n");'
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            perlpack
            ./busyfs/packfs.h.txt
