name: perlpack

on: workflow_dispatch

env:
  MAKEFLAGS: -j2

jobs:
  perlpack:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils gdb cmake git xz wget curl perl gperf p7zip zip python3 strace autoconf automake libtool pkgconfig && ln -sf python3 /usr/bin/python

      - uses: actions/checkout@v4
      
      - name: Build libc_perlpack.a
        run: make libc_perlpack.a

      - name: Build Perl
        run: make build/libperl.a
      
      - name: Build and test perlpackstatic
        run: |
          make perlpackstatic
          ./perlpackstatic
          ./perlpackstatic -e 'use Cwd;print(Cwd::cwd(),"\n");'
          ./perlpackstatic -e 'open(F,"<","/mnt/perlpack/lib/5.35.4/x86_64-linux/Cwd.pm");print(<F>);'
       
      - name: Build and test perlpackstaticzip
        run: |
          git clone --single-branch --depth 1 https://github.com/libarchive/libarchive
          make libarchive/.libs/libarchive.a
          make perlpackstaticzip
          zip -0 - perlpack.c >> perlpackstaticzip
          ./perlpackstaticzip
          ./perlpackstaticzip -e 'use Cwd;print(Cwd::cwd(),"\n");'
          ./perlpackstaticzip -e 'open(F,"<","/mnt/perlpackarchive/perlpack.c");print(<F>);'
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            perlpackstatic
            perlpackstaticzip
            perlpack.h
            libc_perlpack.a
            perlpack
